name: Build PR

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npx lerna bootstrap --ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        env:
          XATA_DATABASE_URL: ${{ secrets.INTEGRATION_TEST_DATABASE_URL }}
          XATA_API_KEY: ${{ secrets.INTEGRATION_TEST_API_KEY }}
          XATA_DATABASE_BRANCH: ${{ secrets.INTEGRATION_TEST_BRANCH }}

      - name: Configure npm registry token
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish beta build
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npx lerna publish 0.0.0-beta.$(git rev-parse --short HEAD) --no-git-tag-version --no-push --dist-tag dev --no-verify-access --yes

      - name: Publish canary build
        if: ${{ github.event_name == 'pull_request' }}
        run: npx lerna publish 0.0.0-alpha.$(git rev-parse --short HEAD) --no-git-tag-version --no-push --dist-tag canary --no-verify-access --yes

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: fc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'xata-bot'
          body-includes: Your pull request has been published to NPM.

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            Your pull request has been published to NPM.

            You can install it by running:

            ```
            npm install @xata/client@0.0.0-alpha.$(git rev-parse --short HEAD)
            npm install @xata/codegen@0.0.0-alpha.$(git rev-parse --short HEAD)
            ```
