name: 🚀 Deployment Tests
on:
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ['cf-workers']

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: 📥 Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./scripts/e2e-tests
          useLockFile: false

      - name: 🚀 Deploy to Cloudflare Workers
        run: node ./${{ matrix.target }}.mjs
        working-directory: ./scripts/e2e-tests
        env:
          CF_ACCOUNT_ID: ${{ secrets.TEST_CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.TEST_CF_API_TOKEN }}
