name: Manual release

on:
  workflow_dispatch:
    inputs:
      bump:
        required: true
        type: choice
        description: Version bump
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          git config user.email "system@xata.io"
          git config user.name "Xata"
          echo ::set-output name=NVMRC::$(cat .nvmrc)
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        id: config

      - name: Use Node.js ${{ steps.config.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.config.outputs.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npx lerna bootstrap --ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        env:
          XATA_DATABASE_URL: ${{ secrets.INTEGRATION_TEST_DATABASE_URL }}
          XATA_API_KEY: ${{ secrets.INTEGRATION_TEST_API_KEY }}
          XATA_DATABASE_BRANCH: ${{ secrets.INTEGRATION_TEST_BRANCH }}

      - name: Bump version
        run: npx lerna version ${{ github.event.inputs.bump }} --yes

      - name: Publish build
        run: npx lerna publish --no-verify-access --yes
