name: Add needs triage label
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issue
        uses: andymckay/labeler@master
        with:
          add-labels: 'needs-triage'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
