name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1' # once every monday

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'npm'

      - name: Check for updates
        uses: mathiasvr/command-output@v1
        id: ncu
        with:
          run: npx -y npm-check-updates -u -t latest --deep --filterVersion "/^[^=]/"

      - name: Install new versions
        run: |
          npm i --force
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: 'Update dependencies'
          committer: 'Xata Bot 🦋 <xata-bot@users.noreply.github.com>'
          title: 'Update dependencies'
          body: |
            This is an autogenerated PR to update the dependencies!

            ------------------------------------------------------------
            ```
            ${{ steps.ncu.outputs.stdout }}
            ```
          branch: update-dependencies-${{ github.run_id }}
